[package]
name = "munyorunyoru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
shrink_pool = "1"
async-channel = "1"
thiserror = "1"
num_cpus = "1"
regex = "1"
pest = "2"
pest_derive = "2"
